apiVersion: v1
kind: Secret
metadata:
    name: project-password
    namespace: project
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ocQmKaeHtcukxkWsejOYFw==,iv:RXwigpWduWtWr5/rPZPN5d3XjVs6M9fRAFMHqceECqY=,tag:gs4ahB8xJJIknWt1X9skhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xcuv6lx2urxspt8k7nd50xjae56g06hj4e683wrm662jr5jlkd3skwxrnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTHZCUm4zaS8yenF0aC83
            RUJQdDhnbTBhVWlCZ1VLKzhybENPWFNCbFdrCnJ0UVEyZjBVYmxyUzJkUnVNOVVF
            OURlZkppL0JCS3hmbnF4Q2ZEVU9lTWcKLS0tIDNjbktSVE8vd3VYb3JQU3NrblZ5
            QkpxKzFYRE5aR0ZWaytocmh2WUxjYnMKq93igv2z3Z1vhTt7V+BJ4uJUUu7slTME
            suTW2H35MdpSoUa2slGQLTMkiKDN1GSmWGgIrw7muidEvgKXjXpb1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-04T16:31:55Z"
    mac: ENC[AES256_GCM,data:YUk2A/Lp6EtUwKmyCRQXEdRpvXqZFcULOOYm/gft6Y6AJAXz8KyYY4EOHOTHxbiUbZq2oy52wEno07WRYNwECqM4/4GvpNfVOPrEoKGBHFbs5r97j1VwjifJJDYYYd4hfnslb/XuKDEjv/O23DnIdBZF7hrFJpryxST+UeBqIqE=,iv:zXQ3QdtdthUI2irsyjmRg+2H+/wr+IOjDt2FyQbaK0M=,tag:doacIBTALFsWthDcHPBlvA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
