apiVersion: batch/v1
kind: CronJob
metadata:
  name: project-job
  namespace: project
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: project-job
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - "curl -d '{\"title\":\"Read '$(curl -w '%{url_effective}' -I -L -s -S https://en.wikipedia.org/wiki/Special:Random -o /dev/null)'\"}' 
            -H \"Content-Type: application/json\" -X POST http://project-svc.project:8081/todos"
          restartPolicy: OnFailure