apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  strategy: {}
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: shared-logs
        persistentVolumeClaim:
          claimName: logs-claim
      containers:
      - image: melxi/hashgenerator
        name: hashgenerator
        volumeMounts:
        - name: shared-logs
          mountPath: /usr/src/app/logs
      - image: melxi/timestamper
        name: timestamper
        volumeMounts:
        - name: shared-logs
          mountPath: /usr/src/app/logs