apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  strategy: {}
  template:
    metadata:
      labels:
        app: project
    spec:
      volumes:
        - name: project-cache
          persistentVolumeClaim:
            claimName: project-claim
      containers:
      - image: melxi/project
        name: project
        volumeMounts:
        - name: project-cache
          mountPath: /usr/src/app/public/img
