apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-rate
  namespace: project
spec:
  metrics:
  - name: cpu-rate
    initialDelay: 2m
    successCondition: result < 0.05
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1657-prometheus.prometheus.svc.cluster.local:9090
        query: scalar(sum(rate(container_cpu_usage_seconds_total{namespace="project"}[10m])))