apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-07-23T16:56:37Z"
    generation: 1
    labels:
      kustomize.toolkit.fluxcd.io/name: project
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: project
    namespace: project
    resourceVersion: "508676"
    uid: c0cf7669-c5bb-4eb2-9052-b37c0b0ac15b
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: project
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: project
      spec:
        containers:
        - image: melxi/project:frontend
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: frontend
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/src/app/public/img
            name: project-cache
        - envFrom:
          - configMapRef:
              name: project-configmap
          - secretRef:
              name: project-password
          image: melxi/project:backend
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3001
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: backend
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3001
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: project-cache
          persistentVolumeClaim:
            claimName: project-claim
  status:
    conditions:
    - lastTransitionTime: "2022-07-23T16:56:37Z"
      lastUpdateTime: "2022-07-23T16:56:37Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2022-07-23T16:56:37Z"
      lastUpdateTime: "2022-07-23T16:56:37Z"
      message: ReplicaSet "project-9fbcb66b5" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-07-23T16:56:37Z"
    generation: 1
    labels:
      kustomize.toolkit.fluxcd.io/name: project
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: project-broadcaster
    namespace: project
    resourceVersion: "508946"
    uid: 2bce23b7-2335-49ba-a3a6-385b08e763fa
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: project
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: project
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: project-configmap
          image: melxi/project:broadcaster
          imagePullPolicy: Always
          name: broadcaster
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2022-07-23T16:56:37Z"
      lastUpdateTime: "2022-07-23T16:56:40Z"
      message: ReplicaSet "project-broadcaster-d94cfb669" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-07-23T16:57:31Z"
      lastUpdateTime: "2022-07-23T16:57:31Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
