apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: applications
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - name: http
      protocol: TCP
      port: 8089
      targetPort: 3002
