apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: project
  namespace: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 30s
      - analysis:
          templates:
          - templateName: cpu-rate
  template:
    metadata:
      labels:
        app: project
    spec:
      volumes:
        - name: project-cache
          persistentVolumeClaim:
            claimName: project-claim
      containers:
      - image: frontend
        imagePullPolicy: Always
        name: frontend
        volumeMounts:
        - name: project-cache
          mountPath: /usr/src/app/public/img
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: "250m"
            memory: "500Mi"
        readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 3000
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          httpGet:
              path: /healthz
              port: 3000
      - image: backend
        imagePullPolicy: Always
        name: backend
        envFrom:
          - configMapRef:
              name: project-configmap
          - secretRef:
              name: project-password
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: "250m"
            memory: "500Mi"
        readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 3001
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          httpGet:
              path: /healthz
              port: 3001
